name: workshoppipeline1
on: 
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: echo "Hello World again"
      - name: sleep 30 sec
        run: sleep 30
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Job 2 Hello World"
      - name: step2
        run: echo "Job 2 Hello World again"
      - name: sleep 5 sec
        run: sleep 5
