name: workshoppipeline1
on: 
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello World"
      - name: step2
       run: echo "Hello World again"
